[package]
name = "json-proof-token-js"
authors = ["dorakemon"]
description = "A minimal Rust-based JSON Web Proof (JWP) library exposed via JavaScript/TypeScript bindings, inspired by json-proof-token (CyberLinks) crate."
version = "0.1.1"
edition = "2021"

[dependencies]
json-proof-token = "0.4.1"
serde-wasm-bindgen = "0.6.5"
serde_json = "1.0.140"
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2", features = ["js"] }
serde = "1.0.219"

[lib]
crate-type = ["cdylib", "rlib"]
